// export const playAria = (actions:any) => {
//     const AriaCorner1 = actions['ARIA-corner-1'].play()
//     const AriaCorner2 =  actions['ARIA-corner-2'].play()
//     const AriaCorner3 = actions['ARIA-corner-3'].play()
//     const AriaCorner4 = actions['ARIA-corner-4'].play()
//     const AriaCupcake1 = actions['ARIA-cupcake-1'].play()
//     const AriaCupcake2 = actions['ARIA-cupcake-2'].play()
//     const AriaCupcake3 = actions['ARIA-cupcake-3'].play()
//     const AriaCupcake4 = actions['ARIA-cupcake-4'].play()
//     const AriaCupcake5 = actions['ARIA-cupcake-5'].play()
//     const AriaCupcake6 = actions['ARIA-cupcake-6'].play()
//     const AriaCupcake7 = actions['ARIA-cupcake-7'].play()
//     const AriaCupcake8 = actions['ARIA-cupcake-8'].play()
//     const AriaCupcake9 = actions['ARIA-cupcake-9'].play()
//     const AriaEndPiece = actions['ARIA-end-piece'].play()
//     const AriaLeftClaw = actions['ARIA-left-claw'].play()
//     const AriaLightBulb = actions['ARIA-lightbulb'].play()
//     const AriaRightClaw = actions['ARIA-right-claw'].play()
//     const AriaRing2 = actions['ARIA-ring-2'].play()
//     const AriaRing3 = actions['ARIA-ring-3'].play()
//     const AriaRing4 = actions['ARIA-ring-4'].play()
//     const AriaRing5 = actions['ARIA-ring-5'].play()

//   }